Added --all-remotes option to gpush.

diff --git a/gpull b/gpull
--- a/gpull
+++ b/gpull
@@ -5,12 +5,38 @@ pname="$(basename "$0")"
 gdirs=("$HOME/.config/gpull-dirs"  "$(dirname "$0")/gdirs")
 for dir in "${gdirs[@]}" ; do
     if [ -r "$dir" ] ; then
-        source "$dir"
+        source "$dir" # should define gsets
         break
     fi
 done
 
 # BASE="$(cd $(dirname "$0") ; cd "$(pwd -P)/../.." ; pwd -P)"
+
+push_all_remotes=0
+psets=()
+goterror=0
+
+
+function usage(){
+    printf "\n"
+    printf "%s usage:\n\n" "$pname"
+    printf "  %s link  # creates the associated symlinks.\n" "$pname"
+    printf "  gstat [gset]\n"
+    printf "  gpull [gset]\n"
+    printf "  gpush [gset] [--all-remotes]\n"
+    printf "\n"
+    printf "gset should be one of: \n" 
+    printf "             %s\n" ${gsets[@]}
+    printf "\n"
+}
+
+function error(){
+    goterror=1
+    printf "%s error: " "$pname" 1>&2
+    printf "$@"                  1>&2
+    printf "\n"                  1>&2
+}
+
 
 if [ "$1"s = links ] ; then
     for link in gpush gstat ; do
@@ -19,42 +45,46 @@ if [ "$1"s = links ] ; then
     exit 0
 fi
 
+
+for arg ; do
+    case "$arg" in
+    --all-remotes)
+        push_all_remotes=1
+        ;;
+    *)
+        gset="$arg"
+        gotit=0
+        for e in ${gsets[@]} ; do 
+            if [ "$gset" = "$e" ] ; then
+                gotit=1
+                break
+            fi
+        done
+
+        if [ $gotit -eq 0 ] ; then
+            error "invalid git set '%s'" "$gset"
+        else
+            psets=( ${psets[@]} $gset )
+        fi
+       ;;
+    esac
+done
+
+
 case "$pname" in
 gpull) op=(pull --all) ;; # (pull --all) ;;
 gpush) op=(push) ;;
 gstat) op=(status) ;;
 *) 
-    printf "%s error: it should be named gpull, gpush or gstat\n" "$pname"
-    printf "use:\n\t gpull link \nto make the symlinks.\n"
-    exit 1
+    error "it should be named gpull, gpush or gstat\nuse:\n\t gpull link \nto make the symlinks.\n"
     ;;
 esac
 
-psets=()
-goterror=0
-
-for gset ; do
-
-    gotit=0
-    for e in ${gsets[@]} ; do 
-        if [ "$gset" = "$e" ] ; then
-            gotit=1
-            break
-        fi
-    done
-
-    if [ $gotit -eq 0 ] ; then
-        printf "%s error: invalid git set '%s', should be one of: \n" "$pname" "$gset"
-        printf "             %s\n" ${gsets[@]}
-        goterror=1
-    fi
-
-    psets=( ${psets[@]} $gset )
-done
-
 if [ $goterror -ne 0 ] ; then
+    usage
     exit 1
 fi
+
 
 if [ ${#psets} -eq 0 ] ; then
     psets=( ${gsets[0]} )
@@ -69,7 +99,14 @@ for pset in ${psets[@]} ; do
             cd "$dir" && (
                 printf "\n########################################################################"
                 printf "\ncd %s\n" "$(pwd)"
-                git "${op[@]}" 
+                if [ ${op[0]} = push -a $push_all_remotes -ne 0 ] ; then
+                    for r in $(git remote) ; do
+                        printf "%s " "$r"
+                        git "${op[@]}" "$r"
+                    done
+                else
+                    git "${op[@]}"
+                fi
             )
         )
     done
