period-cookie: corrected newlines

diff --git a/period-cookie b/period-cookie
--- a/period-cookie
+++ b/period-cookie
@@ -1,40 +1,103 @@
 #!/bin/bash
 
-function period_cookie(){
-    local use_color="${COLOR_PROMPT:-false}"
-    local escape=''
-    local bold="${escape}"'[1m'
-    local underline="${escape}"'[4m'
-    local blink="${escape}"'[5m'
-    local invert="${escape}"'[7m'
-    local no_bold="${escape}"'[22m'
-    local no_underline="${escape}"'[24m'
-    local no_blink="${escape}"'[25m'
-    local no_invert="${escape}"'[27m'
-    local black="${escape}"'[30m'
-    local red="${escape}"'[31m'
-    local green="${escape}"'[32m'
-    local yellow="${escape}"'[33m'
-    local blue="${escape}"'[34m'
-    local magenta="${escape}"'[35m'
-    local cyan="${escape}"'[36m'
-    local white="${escape}"'[37m'
-    local black_back="${escape}"'[40m'
-    local red_back="${escape}"'[41m'
-    local green_back="${escape}"'[42m'
-    local yellow_back="${escape}"'[43m'
-    local blue_back="${escape}"'[44m'
-    local magenta_back="${escape}"'[45m'
-    local cyan_back="${escape}"'[46m'
-    local white_back="${escape}"'[47m'
-    local normal="${escape}"'[0m'
+function minutes(){
+    local count="$1"
+    printf $(( $count * 60 ))
+}
 
+PERIOD=$(minutes 10)
+COOKIE=$(type -path fortune || type -path cookie || type -path /usr/local/bin/cookie)
+
+#--
+pname=$(basename "$0")
+
+escape=''
+bold="${escape}"'[1m'
+underline="${escape}"'[4m'
+blink="${escape}"'[5m'
+invert="${escape}"'[7m'
+no_bold="${escape}"'[22m'
+no_underline="${escape}"'[24m'
+no_blink="${escape}"'[25m'
+no_invert="${escape}"'[27m'
+black="${escape}"'[30m'
+red="${escape}"'[31m'
+green="${escape}"'[32m'
+yellow="${escape}"'[33m'
+blue="${escape}"'[34m'
+magenta="${escape}"'[35m'
+cyan="${escape}"'[36m'
+white="${escape}"'[37m'
+black_back="${escape}"'[40m'
+red_back="${escape}"'[41m'
+green_back="${escape}"'[42m'
+yellow_back="${escape}"'[43m'
+blue_back="${escape}"'[44m'
+magenta_back="${escape}"'[45m'
+cyan_back="${escape}"'[46m'
+white_back="${escape}"'[47m'
+normal="${escape}"'[0m'
+
+function print_cookie(){
+    local output="$1"
+    local line=+-----------------------------------------------------------------------                
+    local text="$("$COOKIE" 2>/dev/null)"
+    if [ -n "$text" ] ; then
+        {
+            if ${COLOR_PROMPT:-false} ; then
+                local back="${black_back}"
+                local fore="${cyan}"
+                local width=$(( ${COLUMNS:-80} - 3 ))
+                printf '\n'
+                printf '%s\n'   "$text" | \
+                    while read line ; do
+                        printf "%s%s %-${width}s %s \n" "${back}" "${fore}" "${line}" "${normal}" 
+                    done
+                printf '\n'
+            else
+                printf '\n%s\n' "$line"
+                printf '%s\n'   "$text" | sed -e '/^$/d' -e 's/^/|  /' 
+                printf '%s\n\n'  "$line"
+            fi;
+        } > $output
+    fi
+}
+
+function print_usage(){
+    
+    cat <<EOF
+${pname} usage:
+
+    ${pname} [-i|--immediate] [-h|--help]
+
+EOF
+}
+
+function period_cookie(){
+    local immediate=false
     local output
-    local line
-    local text
     local period
-    local last
-    local now
+    for arg in "$@" ; do
+        case $arg in
+        (-i|--immediate)
+            immediate=true
+            ;;
+        (-h|--help)
+            print_usage
+            exit 0
+            ;;
+        -*)
+            printf "Invalid option: %s\n" "$arg"
+            print_usage
+            exit 1
+            ;;
+        *)
+            printf "Invalid argument: %s\n" "$arg"
+            print_usage
+            exit 1
+            ;;
+        esac
+    done
     
     if [ "$(uname)" = Darwin ] ; then
         if [ -w /dev/tty ] ; then
@@ -49,37 +112,21 @@ function period_cookie(){
     else
         output=/dev/tty
     fi
-    COOKIE=$(type -path fortune || type -path cookie || type -path /usr/local/bin/cookie)
-    if [ -n "$COOKIE" ] ; then
-        period=$(( 5 * 60 ))
+
+    if $immediate ; then
+        print_cookie "$output"
+    elif [ -n "$COOKIE" ] ; then
+        period=$PERIOD
         last=$(cat ~/.period-cookie 2>/dev/null)
         [ -z "$last" ] && last=0
         now=$(date +%s)
         if [ 0 -ne $(( now - last > period )) ] ; then
             echo "$now" > ~/.period-cookie
-            text="$("$COOKIE" 2>/dev/null)"
-            if [ -n "$text" ] ; then
-                (
-                    if ${COLOR_PROMPT:-false} ; then
-                        local back="${black_back}"
-                        local fore="${cyan}"
-                        local width=$(( ${COLUMNS:-80} - 3 ))
-                        printf '\n'
-                        printf '\n%s\n\n'   "$text"|while read line ; do
-                            printf "%s%s %-${width}s %s \n" "${back}" "${fore}" "${line}" "${normal}" 
-                        done
-                    else
-                        line=+-----------------------------------------------------------------------                
-                        printf '\n%s\n' "$line"
-                        printf '%s\n'   "$text" | sed -e '/^$/d' -e 's/^/|  /' 
-                        printf '%s\n'   "$line"
-                    fi;
-                ) > $output
-            fi
+            print_cookie "$output"
         fi
     fi
 }
 
-period_cookie
+period_cookie "$@"
 
 #### THE END ####
